Now that we've seen the story that the data tells, it's time to perform some hypothesis testing.

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats as st
import statsmodels as sm

df = pd.read_csv (r"C:\Users\Laura-Black\Documents\PhD\Data Scientist\Springboard\Capstone Projects\Drug Abuse ED Visits\Output files\Capstone1DataWrangling.csv", 
                     index_col=0, low_memory=False)

print(df.head())
print(df.head())

              METRO  STRATA  PSU  REPLICATE   CASEWGT  PSUFRAME AGECAT  \
CASEID
1          New York      25  108          2  0.942635         3  18-20
2          New York      29  129          2  5.992011         9   > 65
3       Date County       7   25          1  4.723172         6   > 65
4           Phoenix       8   29          2  4.080147         6  06-11
5            Boston      22   94          2  5.177709        10  25-29

           SEX      RACE  YEAR  ...       DRUGID_22 ROUTE_22  TOXTEST_22  \
CASEID                          ...
1         Male     Black  2011  ...  Not Applicable      NaN         NaN
2         Male  Hispanic  2011  ...  Not Applicable      NaN         NaN
3       Female     Black  2011  ...  Not Applicable      NaN         NaN
4         Male  Hispanic  2011  ...  Not Applicable      NaN         NaN
5         Male  Hispanic  2011  ...  Not Applicable      NaN         NaN

                CASETYPE        DISPOSITION ALCOHOL         NONALCILL  \
CASEID
1                  Other  Detox, Psych Unit     Yes     Illicit Drugs
2       Adverse Reaction    Other Inpatient      No  No Illicit Drugs
3       Adverse Reaction           D/C Home      No  No Illicit Drugs
4       Adverse Reaction    Other Inpatient      No  No Illicit Drugs
5                  Other        Transferred     Yes     Illicit Drugs

                    PHARMA           NONMEDPHARMA  \
CASEID
1       No Pharmaceuticals  No Non-Medical Pharma
2          Pharmaceuticals  No Non-Medical Pharma
3          Pharmaceuticals  No Non-Medical Pharma
4          Pharmaceuticals  No Non-Medical Pharma
5       No Pharmaceuticals  No Non-Medical Pharma

                              ALLABUSE
CASEID
1           All Misuse & Abuse Episode
2       Not All Misuse & Abuse Episode
3       Not All Misuse & Abuse Episode
4       Not All Misuse & Abuse Episode
5           All Misuse & Abuse Episode

[5 rows x 86 columns]
              METRO  STRATA  PSU  REPLICATE   CASEWGT  PSUFRAME AGECAT  \
CASEID
1          New York      25  108          2  0.942635         3  18-20
2          New York      29  129          2  5.992011         9   > 65
3       Date County       7   25          1  4.723172         6   > 65
4           Phoenix       8   29          2  4.080147         6  06-11
5            Boston      22   94          2  5.177709        10  25-29

           SEX      RACE  YEAR  ...       DRUGID_22 ROUTE_22  TOXTEST_22  \
CASEID                          ...
1         Male     Black  2011  ...  Not Applicable      NaN         NaN
2         Male  Hispanic  2011  ...  Not Applicable      NaN         NaN
3       Female     Black  2011  ...  Not Applicable      NaN         NaN
4         Male  Hispanic  2011  ...  Not Applicable      NaN         NaN
5         Male  Hispanic  2011  ...  Not Applicable      NaN         NaN

                CASETYPE        DISPOSITION ALCOHOL         NONALCILL  \
CASEID
1                  Other  Detox, Psych Unit     Yes     Illicit Drugs
2       Adverse Reaction    Other Inpatient      No  No Illicit Drugs
3       Adverse Reaction           D/C Home      No  No Illicit Drugs
4       Adverse Reaction    Other Inpatient      No  No Illicit Drugs
5                  Other        Transferred     Yes     Illicit Drugs

                    PHARMA           NONMEDPHARMA  \
CASEID
1       No Pharmaceuticals  No Non-Medical Pharma
2          Pharmaceuticals  No Non-Medical Pharma
3          Pharmaceuticals  No Non-Medical Pharma
4          Pharmaceuticals  No Non-Medical Pharma
5       No Pharmaceuticals  No Non-Medical Pharma

                              ALLABUSE
CASEID
1           All Misuse & Abuse Episode
2       Not All Misuse & Abuse Episode
3       Not All Misuse & Abuse Episode
4       Not All Misuse & Abuse Episode
5           All Misuse & Abuse Episode

[5 rows x 86 columns]

First, the locations of the cases will be analyzed. Is there a significant difference in the frequency of cases in each of the cities?

Ho: p1 = p2... = p15
Ha: p1 != p2... != p15

In [18]:
nobs =  len(df['METRO'])
table1 = df['METRO'].value_counts()
print(table1)

model1 = sm.stats.proportion.proportions_chisquare(table1, nobs=nobs)
print(model1)
stat1 = 96116.77852955775
p1 = 0.0

print('\n stat = ', stat1)
print('\n p-value = ', p1)

# interpret test-statistic
prob = 0.95
dof1 = nobs - 1
critical1 = st.chi2.ppf(prob, dof1)
print('\n probability=%.3f, critical=%.3f, dof=%.3f' % (prob, critical1, dof1))

# interpret p-value
alpha = 1.0 - prob
print('\n significance=%.3f, p=%.3f' % (alpha, p1))
if p1 <= alpha:
    print('\n Reject H0')
else:
    print('\n Fail to reject H0')

New York           39776
All Other          30860
Boston             24889
Detroit            22502
Chicago            21918
Seattle            18973
Phoenix            13166
Denver             12112
Minneapolis        12049
Houston             9115
San Francisco       8936
Date County         7101
Fort Lauderdale     5352
Oakland             2462
Name: METRO, dtype: int64
(96116.77852955775, 0.0, (array([[ 39776, 189435],
       [ 30860, 198351],
       [ 24889, 204322],
       [ 22502, 206709],
       [ 21918, 207293],
       [ 18973, 210238],
       [ 13166, 216045],
       [ 12112, 217099],
       [ 12049, 217162],
       [  9115, 220096],
       [  8936, 220275],
       [  7101, 222110],
       [  5352, 223859],
       [  2462, 226749]], dtype=int64), array([[ 16372.21428571, 212838.78571429],
       [ 16372.21428571, 212838.78571429],
       [ 16372.21428571, 212838.78571429],
       [ 16372.21428571, 212838.78571429],
       [ 16372.21428571, 212838.78571429],
       [ 16372.21428571, 212838.78571429],
       [ 16372.21428571, 212838.78571429],
       [ 16372.21428571, 212838.78571429],
       [ 16372.21428571, 212838.78571429],
       [ 16372.21428571, 212838.78571429],
       [ 16372.21428571, 212838.78571429],
       [ 16372.21428571, 212838.78571429],
       [ 16372.21428571, 212838.78571429],
       [ 16372.21428571, 212838.78571429]])))

 stat =  96116.77852955775

 p-value =  0.0

 probability=0.950, critical=230324.812, dof=229210.000

 significance=0.050, p=0.000

 Reject H0

Next, the race of the cases will be analyzed. Does the race of the patient vary signifcantly?

Ho: p1 = p2... = p15
Ha: p1 != p2... != p15

In [20]:
nobs =  len(df['RACE'])
table1 = df['RACE'].value_counts()
print(table1)

model2 = sm.stats.proportion.proportions_chisquare(table1, nobs=nobs)
print(model2)
stat2 = 167467.57531270315
p2 = 0.0

print('\n stat = ', stat2)
print('\n p-value = ', p2)

# interpret test-statistic
prob = 0.95
dof2 = nobs - 1
critical2 = st.chi2.ppf(prob, dof2)
print('\n probability=%.3f, critical=%.3f, dof=%.3f' % (prob, critical2, dof2))

# interpret p-value
alpha = 1.0 - prob
print('\n significance=%.3f, p=%.3f' % (alpha, p2))
if p1 <= alpha:
    print('\n Reject H0')
else:
    print('\n Fail to reject H0')

White        109823
Black         50786
Not Doc       32648
Hispanic      30156
All Other      5798
Name: RACE, dtype: int64
(167467.57531270315, 0.0, (array([[109823, 119388],
       [ 50786, 178425],
       [ 32648, 196563],
       [ 30156, 199055],
       [  5798, 223413]], dtype=int64), array([[ 45842.2, 183368.8],
       [ 45842.2, 183368.8],
       [ 45842.2, 183368.8],
       [ 45842.2, 183368.8],
       [ 45842.2, 183368.8]])))

 stat =  167467.57531270315

 p-value =  0.0

 probability=0.950, critical=230324.812, dof=229210.000

 significance=0.050, p=0.000

 Reject H0

Now, the independence of disposition vs. casetype will be analyzed.

Ho: the population frequencies are equal to the expected frequencies
Ha: the population frequencies are not equal to the expected frequencies.

In [27]:
crosstab = pd.crosstab(df['CASETYPE'], df['DISPOSITION'])
crosstab

DISPOSITION,D/C Home,"Detox, Psych Unit",Detox/Treat Referral,Died,ICU,Left Against Medical Advice,Not Documented,Other,Other Inpatient,Police/Jail,Surgery,Transferred
CASETYPE,,,,,,,,,,,,
Accidential Ingestion,2733,0,0,0,64,21,13,18,263,3,1,137
Adverse Reaction,63147,296,100,32,1469,677,501,390,20068,143,113,1160
Alcohol (Age<21),6119,119,112,2,67,50,30,70,332,310,14,196
Malicious Poisoning,657,13,12,1,4,22,3,19,40,4,2,16
Other,47222,8752,3800,103,1625,1844,989,1433,11785,3158,226,6691
Overmedication,8337,1101,334,30,1590,269,168,228,4565,115,10,1399
Seeking Detox,4085,5161,2751,0,32,281,107,331,1017,32,1,1043
Suicide Attempt,1631,1326,358,7,1080,27,101,130,2145,72,12,2144

In [23]:
st.chi2_contingency(crosstab)

(73287.06461902295,
 0.0,
 77,
 array([[1.90077066e+03, 2.37974198e+02, 1.05972885e+02, 2.48362862e+00,
         8.41737220e+01, 4.52871939e+01, 2.71354167e+01, 3.71692763e+01,
         5.70737857e+02, 5.44553316e+01, 5.37882999e+00, 1.81461003e+02],
        [5.14756507e+04, 6.44468951e+03, 2.86990080e+03, 6.72602973e+01,
         2.27954756e+03, 1.22644348e+03, 7.34866791e+02, 1.00659839e+03,
         1.54564163e+04, 1.47473006e+03, 1.45666587e+02, 4.91422949e+03],
        [4.33618784e+03, 5.42885499e+02, 2.41753699e+02, 5.66584937e+00,
         1.92023729e+02, 1.03312716e+02, 6.19034514e+01, 8.47934829e+01,
         1.30201219e+03, 1.24227794e+02, 1.22706109e+01, 4.13963143e+02],
        [4.63360323e+02, 5.80121547e+01, 2.58335377e+01, 6.05446510e-01,
         2.05194471e+01, 1.10398846e+01, 6.61493558e+00, 9.06093948e+00,
         1.39131608e+02, 1.32748472e+01, 1.31122416e+00, 4.42356519e+01],
        [5.12021922e+04, 6.41045283e+03, 2.85465478e+03, 6.69029846e+01,
         2.26743772e+03, 1.21992814e+03, 7.30962894e+02, 1.00125095e+03,
         1.53743059e+04, 1.46689572e+03, 1.44892749e+02, 4.88812321e+03],
        [1.06029463e+04, 1.32747612e+03, 5.91141708e+02, 1.38542653e+01,
         4.69540842e+02, 2.52622632e+02, 1.51367744e+02, 2.07338976e+02,
         3.18371016e+03, 3.03764662e+02, 3.00043802e+01, 1.01223221e+03],
        [8.67179137e+03, 1.08569784e+03, 4.83474820e+02, 1.13309353e+01,
         3.84021583e+02, 2.06611511e+02, 1.23798561e+02, 1.69575540e+02,
         2.60384892e+03, 2.48438849e+02, 2.45395683e+01, 8.27870504e+02],
        [5.27810063e+03, 6.60811846e+02, 2.94267775e+02, 6.89659310e+00,
         2.33735392e+02, 1.25754449e+02, 7.53502057e+01, 1.03212442e+02,
         1.58483709e+03, 1.51212730e+02, 1.49360502e+01, 5.03884796e+02]]))

In [28]:
p3 = 0.0

# interpret p-value
alpha = 1.0 - prob
print('\n significance=%.3f, p=%.3f' % (alpha, p3))
if p1 <= alpha:
    print('\n Reject H0')
else:
    print('\n Fail to reject H0')

 significance=0.050, p=0.000

 Reject H0

Now, the independence of sex vs. drugid1 will be analyzed.

Ho: the population frequencies are equal to the expected frequencies
Ha: the population frequencies are not equal to the expected frequencies.

In [30]:
crosstab2 = pd.crosstab(df['SEX'], df['DRUGID_1'])
crosstab2

DRUGID_1,THALIDOMIDE,"2,5-DIMETHOXY-4-ETHYL-PHENETHYLAMINE","2,5-DIMETHOXY-4-IODOPHENETHYLAMINE","3,4-METHYLENEDIOXYPYROVALERONE","4-BROMO-2,5-DIMETHOXYPHENETHYLAMINE",4-METHOXYMETHCATHINONE,4-METHYLMETHCATHINONE,5-HYDROXYTRYPTOPHAN,ABACAVIR-LAMIVUDINE,ABATACEPT,...,ZIDOVUDINE,ZILEUTON,ZINC,ZINC SULFATE,ZIPRASIDONE,ZOLEDRONIC ACID,ZOLMITRIPTAN,ZOLPIDEM,ZONISAMIDE,ZOSTER VACCINE LIVE
SEX,,,,,,,,,,,,,,,,,,,,,
Female,6,1,1,1,0,0,1,2,1,4,...,2,2,19,1,173,28,7,803,17,7
Male,2,5,2,7,1,1,10,1,3,3,...,2,0,8,0,112,10,1,486,9,2
Not Doc,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [31]:
st.chi2_contingency(crosstab2)

(27805.688966902777,
 0.0,
 3102,
 array([[3.84030435e+00, 2.88022826e+00, 1.44011413e+00, ...,
         6.18769038e+02, 1.24809891e+01, 4.32034239e+00],
        [4.15725249e+00, 3.11793937e+00, 1.55896968e+00, ...,
         6.69837307e+02, 1.35110706e+01, 4.67690905e+00],
        [2.44316372e-03, 1.83237279e-03, 9.16186396e-04, ...,
         3.93654755e-01, 7.94028210e-03, 2.74855919e-03]]))

In [32]:
p4 = 0.0

# interpret p-value
alpha = 1.0 - prob
print('\n significance=%.3f, p=%.3f' % (alpha, p4))
if p1 <= alpha:
    print('\n Reject H0')
else:
    print('\n Fail to reject H0')

 significance=0.050, p=0.000

 Reject H0

This part of Capstone Project 1 has tested the proportion and independence of some of the variables.